export default (`
  Spicy jalapeno bacon ipsum dolor amet pork belly pork chop jerky frankfurter filet mignon pork loin chuck. Capicola pancetta turducken tri-tip swine burgdoggen sausage. Cupim jerky sausage sirloin bresaola leberkas porchetta beef ribs ham chicken flank meatloaf ribeye kevin. Pancetta meatball jowl cupim. Ground round strip steak frankfurter pork hamburger tail beef venison prosciutto corned beef boudin swine turkey jowl shank. Jowl swine ball tip sausage.

  Shankle prosciutto shank filet mignon drumstick pork loin fatback kevin tongue. Burgdoggen bresaola tail sirloin sausage ground round salami meatball jerky biltong tri-tip. Pork loin meatloaf ball tip doner tri-tip turkey. Jowl sirloin corned beef kielbasa burgdoggen pork belly tri-tip biltong.

  Drumstick ham hock pancetta meatloaf bacon turducken hamburger swine tri-tip shoulder strip steak pork loin pork chop. Picanha salami pork loin, boudin prosciutto ham ground round chicken shoulder flank venison. Pancetta pastrami venison, tenderloin buffalo leberkas beef turducken. Tongue ribeye pork bresaola corned beef, flank short loin venison. Sausage pancetta short loin pork chop jowl fatback hamburger, short ribs beef ribs drumstick strip steak cow flank swine biltong. Pig andouille pancetta short loin prosciutto turducken.

  Ground round landjaeger beef ribs, burgdoggen pancetta swine shank turkey pork chop. Tenderloin cupim meatloaf sausage ball tip, drumstick ribeye porchetta. Spare ribs meatloaf beef bacon biltong flank t-bone pork chop drumstick short ribs sirloin jerky pork. Cupim rump tenderloin beef, ball tip kielbasa pork drumstick salami burgdoggen ham pancetta. Burgdoggen jerky ham hock kevin shoulder strip steak.

  Pancetta swine landjaeger short ribs alcatra ball tip pig kevin chuck beef pork meatloaf andouille bresaola. Tail biltong pancetta shankle spare ribs leberkas strip steak ham hock shank kevin frankfurter meatball. Salami frankfurter pork loin boudin corned beef tail doner swine, spare ribs burgdoggen. Tenderloin strip steak swine filet mignon picanha, kielbasa sirloin meatball beef alcatra ground round. Shankle alcatra hamburger, leberkas bresaola short ribs ham hock boudin. Shoulder bresaola picanha biltong t-bone. Cupim bacon spare ribs ball tip tri-tip meatloaf.

  Kevin landjaeger alcatra shoulder. T-bone pastrami pancetta ham hock shoulder pork loin. Shankle filet mignon spare ribs landjaeger venison pig rump tri-tip capicola. Flank pork loin cow, capicola chuck sirloin beef ribs buffalo shankle meatball. Tri-tip ham ball tip turducken venison.

  Jowl pork belly turducken shoulder shankle kielbasa cow tri-tip tail ground round strip steak tenderloin beef ribs chicken drumstick. Kielbasa pig fatback t-bone ball tip turducken ham. Picanha pork chop pig strip steak tenderloin chuck frankfurter brisket sirloin chicken. Chuck ribeye biltong, andouille frankfurter pork jerky chicken.

  Short loin alcatra pancetta pork belly hamburger. Strip steak porchetta jowl, ribeye beef swine bacon pork loin burgdoggen landjaeger short ribs ball tip picanha. Flank ham chicken pork loin t-bone short ribs. Drumstick chicken capicola frankfurter hamburger ground round salami tri-tip meatloaf pancetta burgdoggen cow. Short loin fatback pork belly biltong, jowl beef ribs corned beef meatloaf pork flank.

  Boudin ham bresaola strip steak meatloaf pork belly sausage venison short ribs flank drumstick jowl prosciutto brisket. Salami cow shank, beef shoulder sirloin shankle ribeye doner pork loin hamburger chuck meatloaf. Ribeye jerky pork belly porchetta brisket cow sausage meatball, strip steak t-bone doner. Biltong kevin drumstick boudin pork loin chicken ham hock tongue spare ribs. Prosciutto jowl pastrami strip steak short loin. T-bone cow sirloin meatloaf tail, corned beef filet mignon ball tip tongue tenderloin chicken.

  Porchetta corned beef ball tip rump. Tenderloin porchetta jowl pork loin ham hock ham pastrami cupim shoulder flank biltong andouille bacon. Pancetta tail hamburger shoulder, doner chuck landjaeger fatback picanha turducken bacon spare ribs. Leberkas turkey pork loin, short ribs sausage corned beef tail ham hock.

  Rump sirloin meatloaf, salami pork loin jerky meatball tongue filet mignon strip steak boudin t-bone. Corned beef buffalo drumstick, leberkas frankfurter fatback brisket spare ribs beef meatloaf capicola. Swine shoulder kevin tenderloin venison, tongue jowl beef ribs ball tip biltong picanha turducken turkey porchetta chicken. Chuck flank turkey meatball, spare ribs bresaola jerky beef ribs pork belly shoulder venison buffalo. Short ribs kielbasa andouille, beef buffalo picanha tongue meatball frankfurter pig kevin bresaola. Ground round chicken andouille t-bone shoulder pig.

  Pastrami spare ribs ground round short loin landjaeger cupim, drumstick kevin jowl ham ball tip pig. Meatloaf ham hock shankle pancetta. Picanha alcatra prosciutto filet mignon, shoulder shankle meatloaf beef ball tip cow hamburger pork chop bacon. Turkey tail andouille strip steak buffalo hamburger meatloaf, pancetta boudin kielbasa biltong chuck jerky shoulder.
`)
